name: darmok
main: me.botsko.darmok.Darmok
version: 1.0
softdepend: [Vault,Essentials]
commands:
   darmok:
      description: Darmok
      usage: /darmok ?
   ch:
      description: Channel commands
      usage: /ch ?