name: darmok
main: me.botsko.darmok.Darmok
version: ${describe}
softdepend: [Vault,Essentials,Towny]
commands:
   darmok:
      description: Darmok
      usage: /darmok ?
   ch:
      description: Channel commands
      usage: /ch ?